Dojo/Models/MartialArt.cs
using System.Collections.Generic;
using System;

namespace Dojo.Models
{
  public class MartialArt
  {
    public MartialArt()
    {
      this.Senseis = new HashSet<Sensei>();
    }
    public int MartialArtId { get; set; }
    public string Type { get; set; }
    public virtual ICollection<Sensei> Senseis { get; set; }
  }
}

Dojo/Controllers/MartialArtController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using System.Collections;
using System.Linq;
using Dojo.Models;
using System;

namespace Dojo.Controllers
{
  public class MartialArtController : Controller
  {
    private readonly DojoContext _db;

    public MartialArtController(DojoContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      ViewBag.PageTitle = ("Martial Arts");
      ViewBag.Header = ("MARTIAL ARTS");
      List<MartialArt> model = _db.MartialArts.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.PageTitle = ("Create Martial Art");
      ViewBag.Header = ("MARTIAL ART CREATION");
      return View();
    }

    [HttpPost]
    public ActionResult Create(MartialArt martialArt)
    {
      _db.MartialArts.Add(martialArt);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      MartialArt thisMartialArt = _db.MartialArts.FirstOrDefault(martialArt => martialArt.MartialArtId == id);
      ViewBag.PageTitle = (thisMartialArt.Type + " Details");
      ViewBag.Header = (thisMartialArt.Type + " Details");
      return View(thisMartialArt);
    }

    public ActionResult Delete(int id)
    {
      MartialArt thisMartialArt = _db.MartialArts.FirstOrDefault(martialArt => martialArt.MartialArtId == id);
      ViewBag.PageTitle = ("Delete " + thisMartialArt.Type);
      ViewBag.Header = ("Delete " + thisMartialArt.Type + "?");
      return View(thisMartialArt);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      MartialArt thisMartialArt = _db.MartialArts.FirstOrDefault(martialArt => martialArt.MartialArtId == id);
      _db.MartialArts.Remove(thisMartialArt);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Dojo/Controllers/SenseiController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Dojo.Models;
using System.Collections.Generic;
using System.Linq;

namespace Dojo.Controllers
{
  public class SenseiController : Controller
  {
    private readonly DojoContext _db;

    public SenseiController(DojoContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      ViewBag.PageTitle = ("Senseis");
      ViewBag.Header = ("Senseis");
      List<Sensei> model = _db.Senseis.Include(sensei => sensei.MartialArt).ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.PageTitle = ("Add Sensei");
      ViewBag.Header = ("Add Sensei");
      ViewBag.MartialArtId = new SelectList(_db.MartialArts, "MartialArtId", "Type");
      ViewBag.Count = _db.MartialArts.ToList();
      return View();
    }

    [HttpPost]
    public ActionResult Create(Sensei sensei)
    {
      _db.Senseis.Add(sensei);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Sensei thisSensei = _db.Senseis.FirstOrDefault(sensei => sensei.SenseiId == id);
      ViewBag.PageTitle = (thisSensei.Name + " Details");
      ViewBag.Header = ("Sensei " + thisSensei.Name + " Details");
      ViewBag.currentMartialArt = _db.MartialArts.FirstOrDefault(martialArt => martialArt.MartialArtId == thisSensei.MartialArtId);
      return View(thisSensei);
    }

    public ActionResult Edit(int id)
    {
      var thisSensei = _db.Senseis.FirstOrDefault(sensei => sensei.SenseiId == id);
      ViewBag.MartialArtId = new SelectList(_db.MartialArts, "MartialArtId", "Type");
      return View(thisSensei);
    }

    [HttpPost]
    public ActionResult Edit(Sensei sensei)
    {
      _db.Entry(sensei).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisSensei = _db.Senseis.FirstOrDefault(sensei => sensei.SenseiId == id);
      return View(thisSensei);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisSensei = _db.Senseis.FirstOrDefault(sensei => sensei.SenseiId == id);
      _db.Senseis.Remove(thisSensei);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Dojo/Views/MartialArt/Create.cshtml
@{
  Layout = "_Layout";
}

@model Dojo.Models.MartialArt

@using (Html.BeginForm())
{
  @Html.Label("Martial Art Type")<span>  :  </span>
  @Html.TextBoxFor(model => model.Type, new {required = "required", @class="textBox" })
  <input type="submit" value="Add new Martial Art" class="htmlButton"/>
}
<hr/>
@Html.ActionLink("Show all Martial Arts", "Index", "MartialArt", null, new { @class="htmlButton"})

Dojo/Views/MartialArt/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Dojo.Models.MartialArt;

<h4>Are you sure you want to delete @Model.Type</h4>
@Html.DisplayNameFor(model => model.Type): @Html.DisplayFor(model => model.Type)
  @using (Html.BeginForm())
  {
    <input type="submit" value="Delete" class="htmlButton"/>
  }
<hr/>
@Html.ActionLink("Back to List", "Index", "MartialArt", null, new { @class="htmlButton" })

Dojo/Views/MartialArt/Details.cshtml
@{
  Layout = "_Layout";
}

@using Dojo.Models;
@model Dojo.Models.MartialArt;

@if (Model.Senseis.Count == 0)
{
  <h4>There are no Senseis instructing @Model.Type</h4>
  @Html.ActionLink("Add Sensei", "Create", "Sensei", null, new { @class="htmlButton"})
}
else
{ 
  <h4>Senseis: </h4>
  <ul>
  @foreach (Sensei sensei in Model.Senseis)
  {
    <li>@Html.ActionLink($"{sensei.Name}", "Details", "Sensei", new { id = sensei.SenseiId })</li>
  }
  </ul>
  @Html.ActionLink("Add Sensei", "Create", "Sensei", null, new { @class="htmlButton"}) 
}


@Html.ActionLink("Delete " + $"{Model.Type}", "Delete", "MartialArt", new { id = Model.MartialArtId }, new { @class="htmlButton"})

Dojo/Views/MartialArt/Index.cshtml
@{
  Layout = "_Layout";
}

@using Dojo.Models;

@if(@Model.Count == 0)
{
  <h4>No Martial Arts have been added yet.</h4>
}

<ul>
  @foreach (MartialArt art in Model)
  {
    <li>@Html.ActionLink($"{art.Type}", "Details", new { id = art.MartialArtId})</li>
  }
</ul>

<hr>

@Html.ActionLink("Add Martial Art", "Create", "MartialArt", null, new { @class="htmlButton"})