Dojo/Models/Disciple.cs
using System.Collections.Generic;
using System;

namespace Dojo.Models
{
  public class Disciple
  {
    public Disciple()
    {
      this.JoinEntities = new HashSet<DiscipleSensei>();
    }
    public int DiscipleId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<DiscipleSensei> JoinEntities { get; set; }
  }
}

Dojo/Controllers/DiscipleController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Dojo.Models;
using System.Collections.Generic;
using System.Linq;

namespace Dojo.Controllers
{
  public class DiscipleController : Controller
  {
    private readonly DojoContext _db;

    public DiscipleController(DojoContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      ViewBag.PageTitle = ("Disciples");
      ViewBag.Header = ("Disciples");
      return View(_db.Disciples.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.PageTitle = ("Add Disciple");
      ViewBag.Header = ("Add Disciples");      
      ViewBag.Count = _db.Senseis.ToList();
      ViewBag.SenseiId = new SelectList(_db.Senseis, "SenseiId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Disciple disciple, int senseiId)
    {
      _db.Disciples.Add(disciple);
      _db.SaveChanges();
      if (senseiId != 0)
      {
        _db.DiscipleSensei.Add(new DiscipleSensei() { SenseiId = senseiId, DiscipleId = disciple.DiscipleId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Disciple thisDisciple = _db.Disciples.FirstOrDefault(sensei => sensei.DiscipleId == id);
      ViewBag.PageTitle = (thisDisciple.Name + " Details");
      ViewBag.Header = ("Disciple " + thisDisciple.Name + " Details");
      return View(thisDisciple);
    }

    public ActionResult Edit(int id)
    {
      var thisDisciple = _db.Disciples.FirstOrDefault(sensei => sensei.DiscipleId == id);
      ViewBag.SenseiId = new SelectList(_db.Senseis, "SenseiId", "Name");
      return View(thisDisciple);
    }

    [HttpPost]
    public ActionResult Edit(Disciple sensei, int SenseiId)
    {
      if (SenseiId != 0)
      {
        _db.DiscipleSensei.Add(new DiscipleSensei() { SenseiId = SenseiId, DiscipleId = sensei.DiscipleId });
      }
      _db.Entry(sensei).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisDisciple = _db.Disciples.FirstOrDefault(sensei => sensei.DiscipleId == id);
      return View(thisDisciple);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisDisciple = _db.Disciples.FirstOrDefault(sensei => sensei.DiscipleId == id);
      _db.Disciples.Remove(thisDisciple);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteSensei(int joinId)
    {
      var joinEntry = _db.DiscipleSensei.FirstOrDefault(entry => entry.DiscipleSenseiId == joinId);
      _db.DiscipleSensei.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddSensei(int id)
    {
      var thisDisciple = _db.Disciples.FirstOrDefault(disciple => disciple.DiscipleId == id);
      ViewBag.PageTitle = (thisDisciple.Name + " Enroll");
      ViewBag.Header = ("Disciple " + thisDisciple.Name + " Enrollment");
      ViewBag.SenseiId = new SelectList(_db.Senseis, "SenseiId", "Name");
      return View(thisDisciple);
    }

    [HttpPost]
    public ActionResult AddSensei(Disciple disciple, int senseiId)
    {
      if (senseiId != 0)
      {
        _db.DiscipleSensei.Add(new DiscipleSensei() { SenseiId = senseiId, DiscipleId = disciple.DiscipleId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }
  }
}

Dojo/Controllers/SenseiController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Dojo.Models;
using System.Collections.Generic;
using System.Linq;

namespace Dojo.Controllers
{
  public class SenseiController : Controller
  {
    private readonly DojoContext _db;

    public SenseiController(DojoContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      ViewBag.PageTitle = ("Senseis");
      ViewBag.Header = ("Senseis");
      List<Sensei> model = _db.Senseis.Include(sensei => sensei.MartialArt).ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.PageTitle = ("Add Sensei");
      ViewBag.Header = ("Add Sensei");
      ViewBag.MartialArtId = new SelectList(_db.MartialArts, "MartialArtId", "Type");
      ViewBag.Count = _db.MartialArts.ToList();
      return View();
    }

    [HttpPost]
    public ActionResult Create(Sensei sensei)
    {
      _db.Senseis.Add(sensei);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Sensei thisSensei = _db.Senseis.FirstOrDefault(sensei => sensei.SenseiId == id);
      ViewBag.PageTitle = (thisSensei.Name + " Details");
      ViewBag.Header = ("Sensei " + thisSensei.Name + " Details");
      ViewBag.currentMartialArt = _db.MartialArts.FirstOrDefault(martialArt => martialArt.MartialArtId == thisSensei.MartialArtId);
      return View(thisSensei);
    }

    public ActionResult Edit(int id)
    {
      var thisSensei = _db.Senseis.FirstOrDefault(sensei => sensei.SenseiId == id);
      ViewBag.MartialArtId = new SelectList(_db.MartialArts, "MartialArtId", "Type");
      return View(thisSensei);
    }

    [HttpPost]
    public ActionResult Edit(Sensei sensei)
    {
      _db.Entry(sensei).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisSensei = _db.Senseis.FirstOrDefault(sensei => sensei.SenseiId == id);
      return View(thisSensei);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisSensei = _db.Senseis.FirstOrDefault(sensei => sensei.SenseiId == id);
      _db.Senseis.Remove(thisSensei);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Dojo/Views/Disciple/AddSensei.cshtml
@{
  Layout = "_Layout";
}

@model Dojo.Models.Disciple

<h6>Enroll Disciple @Model.Name into a new class</h6>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.DiscipleId)

  @Html.Label("Select Sensei")<span>  :  </span>
  @Html.DropDownList("SenseiId")

  <input type="submit" value="Save" />
}

Dojo/Views/Disciple/Create.cshtml
@{
  Layout = "_Layout";
}

@using Dojo.Models
@model Dojo.Models.Sensei;

@if(ViewBag.Count.Count == 0)
{
  <p>You can not add Disciples until you have a Sensei.</p>
  @Html.ActionLink("Add Sensei", "Create", "Sensei", null, new { @class="htmlButton"})
}
else
{
  @using (Html.BeginForm())
  {
    @Html.Label("Disciple Name")<span>  :  </span>
    @Html.TextBoxFor(model => model.Name, new {required = "required", @class="textBox" })
    @Html.Label("Sensei")<span>  :  </span>
    @Html.DropDownList("SenseiId")
    <input type="submit" value="Add new Disciple" class="htmlButton"/>
  }
}

<hr/>

@Html.ActionLink("Show all Senseis", "Index", "Sensei", null, new { @class="htmlButton"})

Dojo/Views/Disciple/Details.cshtml
@{
  Layout = "_Layout";
}

@using Dojo.Models;
@model Dojo.Models.Disciple;


@if(Model.JoinEntities.Count == 0)
{
  <h6>Model.Name is not enrolled in any classes</h6> 
}
else
{
  <h6>Currently enrolled in @Model.JoinEntities.Count classes.</h6>
  <p>List of Senseis: </p>
  <ul>
    @foreach(var join in Model.JoinEntities)
    {
      <li>@Html.ActionLink($"{join.Sensei.Name}", "Details", "Sensei", new { id = join.Sensei.SenseiId})</li>
    }
  </ul>
}
<br>
<br>
<p>Contact Information: </p>

<br>

@Html.ActionLink("Enroll", "AddSensei", "Disciple", new { id = Model.DiscipleId }, new { @class="htmlButton"}) 
@Html.ActionLink("Delete " + $"{Model.Name}", "Delete", "Sensei", new { id = Model.DiscipleId }, new { @class="htmlButton"})

Dojo/Views/Disciple/Index.cshtml
@{
  Layout = "_Layout";
}

@using Dojo.Models;

@if(@Model.Count == 0)
{
  <h4>No Disciples have been added yet.</h4>
}

<ul>
  @foreach (Disciple disciple in Model)
  {
    <li>@Html.ActionLink($"{disciple.Name}", "Details", new { id = disciple.DiscipleId })</li>
  }
</ul>

<hr>

@Html.ActionLink("Add Disciple", "Create", "Disciple", null, new { @class="htmlButton"})